import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import NavbarApp from '@/component/navBar';
import ShowComponent from '@/component/showComponents';
import Footer from '@/component/footer';
import AppProvider from '@/context';
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Just do it',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <NavbarApp />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
