import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import NavbarApp from '@/component/navBar';
import ShowComponent from '@/component/showComponents';
import Footer from '@/component/footer';
import AuthProvider from '@/context';
import { Toaster } from 'sonner';
import ChatBotComponent from "@/component/chatBot";


const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Just do it',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       
        <AuthProvider>
          <ShowComponent>
          <NavbarApp />
          </ShowComponent>
            <Toaster position="top-center"
            toastOptions={{
              style: {
                background: '#04ff6899',
                color: '#000000',
                fontWeight: 'bold',
                fontSize: '15px',
                borderRadius: '8px',
              },
            }}
            />
            <ChatBotComponent />
          {children}
          <ShowComponent>
          <Footer />
          </ShowComponent>
        </AuthProvider>
      </body>
    </html>
  );
}