import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import NavbarApp from '@/component/navBar';
import ShowComponent from '@/component/showComponents';
import Footer from '@/component/footer';
import AuthProvider from '@/context';
import { Toaster } from 'sonner';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Just do it',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       
        <AuthProvider>
          <ShowComponent>
          <NavbarApp />
          </ShowComponent>
            <Toaster position="top-center"
            toastOptions={{
              style: {
                background: '#fbff0099',
                color: '#000000',
                borderRadius: '0.75rem',
                padding: '0.5rem 1rem',
                fontSize: '1.25rem',
              },
            }}
            />
          {children}
          <ShowComponent>
          <Footer />
          </ShowComponent>
        </AuthProvider>
      </body>
    </html>
  );
}